services:
  database:
    image: postgres:latest
    env_file:
      - ./database.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    env_file:
      - ./database.env
      - ./jwt.env
      - ./account.env
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      database:
        condition: service_healthy