server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://database:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.data: DEBUG
    org.springframework.security: DEBUG

token:
  signing:
    key: ${TOKEN_SIGNING_KEY}

initial-account:
  email: ${INITIAL_ACCOUNT_EMAIL}
  password: ${INITIAL_ACCOUNT_PASSWORD}