server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://database:5432/mydatabase
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.data: DEBUG
    org.springframework.security: DEBUG

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
